# Generated by Django 5.2.16 on 2026-07-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='generated_posts/')),
                ('prompt', models.TextField()),
                ('master_caption', models.TextField()),
                ('hashtags', models.JSONField()),
                ('generated_posts', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('generated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to='core.generatedpost')),
            ],
        ),
    ]
