# Generated by Django 5.2.16 on 2026-08-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_generatedpost_user_publishedpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpost',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='target_audience',
            field=models.CharField(blank=True, default='General Audience', max_length=255),
        ),
        migrations.AddField(
            model_name='generatedpost',
            name='tone',
            field=models.CharField(blank=True, default='casual', max_length=50),
        ),
    ]
