# Generated by Django 5.2.16 on 2026-08-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_generatedpost_is_draft_generatedpost_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpost',
            name='comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
